---
    - name: Ensure that Mysql is running and starts on boot
      service: name=mysql state=started enabled=true

    - name: Update Mysql root password for all root accounts
      mysql_user: name=root host=localhost password={{ root_db_password }}
      
    - name: Removes anonymous user account for localhost
      mysql_user: name='' host=localhost state=absent
      
    - name: Remove the test database
      mysql_db: name=test state=absent
      
